# Generated by Django 4.0.6 on 2022-08-11 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField(default=django.utils.timezone.now)),
                ('slider_message1', models.TextField(blank=True, null=True)),
                ('slider_message2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
