# Generated by Django 4.0.6 on 2022-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mziweb', '0002_remove_launch_slider_message1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='slider1_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='slider2_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
